/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import controle.MetodosEstaticos;
import controle.Validacao;
import modelo.Comum;
import modelo.Sala;
import modelo.Usuario;

import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import javax.swing.JFormattedTextField;
import java.awt.Font;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JPasswordField;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;
import javax.swing.AbstractListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import java.awt.Color;
import javax.swing.UIManager;
import java.awt.SystemColor;

/**
 *
 * @author Carlos Jr
 */
public class UsuarioComum extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioComum
     */
	
	private JLabel lbConfirmacaoCadastro;
	private JFormattedTextField ftCpfCadastro;
	private JTextPane tpnDadosUsuario;
    private javax.swing.JTextField tfNomeCadastro;
    private javax.swing.JTextField tfEmailCadastro;
    private JPasswordField ptSenhaCadastro;
    private JPasswordField ptConSenhaCadastro;
    private javax.swing.JComboBox cbTipoUsuarioCadastro;
    private javax.swing.JButton btLimparPesqUsuario;
    private JTextPane tpDadosPesqSala;
    private javax.swing.JButton btPesqSala;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JTextField tfNomeSalaPesquisa;
    private JTextField tfCidadePesquisa;
    private javax.swing.JTextField tfNomeLocalPesq;
    private JComboBox cbTerminoReuniao;
    private JFormattedTextField ftfDataReuniao;
    
    public UsuarioComum() {
        initComponents();
    }
    
 // Declarando objetos uteis
 	Statement st = null;
 	PreparedStatement ps = null;
 	ResultSet rt = null;
 	Comum usuario ;
 	Connection conect = null;
 	Usuario user;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnCadastro = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNomeCadastro = new javax.swing.JTextField();
        cbTipoUsuarioCadastro = new javax.swing.JComboBox();
        cbTipoUsuarioCadastro.setEnabled(false);
        tfEmailCadastro = new javax.swing.JTextField();
        btCancelarCadastro = new javax.swing.JButton();
        btCancelarCadastro.setAction(acLimparCadUsuario);
        btSalvarCadastro = new javax.swing.JButton();
        btSalvarCadastro.setAction(acCadUsuario);
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfPesquisarCpf = new javax.swing.JTextField();
        btPesquisarUsuario = new javax.swing.JButton();
        btPesquisarUsuario.setAction(acPesqUsuario);
        btLimparPesqUsuario = new javax.swing.JButton();
        btLimparPesqUsuario.setAction(acLimpPesqUsuario);
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("e-Meeting - Usuário Comum");

        jTabbedPane1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Usu\u00E1rio");

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText("Perfil de Acesso");

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setText("CPF");

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setText("E-mail");

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setText("Senha");

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setText("Confirme a senha");

        cbTipoUsuarioCadastro.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        cbTipoUsuarioCadastro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comum", "Coordenador", "Gestor de Recursos" }));

        tfEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        btCancelarCadastro.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btCancelarCadastro.setText("Limpar");

        btSalvarCadastro.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btSalvarCadastro.setText("Salvar");
        
        lbConfirmacaoCadastro = new JLabel("Verifique seus dados antes de salvar");
        
        ftCpfCadastro = new JFormattedTextField();
        
        ptSenhaCadastro = new JPasswordField();
        
        ptConSenhaCadastro = new JPasswordField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGap(86)
        							.addComponent(jLabel1))
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGap(36)
        							.addComponent(btCancelarCadastro)
        							.addGap(54)
        							.addComponent(btSalvarCadastro)))
        					.addGap(0, 66, Short.MAX_VALUE))
        				.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(tfNomeCadastro, 300, 300, 300)
        						.addComponent(cbTipoUsuarioCadastro, 0, 300, Short.MAX_VALUE)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(263))
        						.addComponent(tfEmailCadastro, 300, 300, 300)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel2, Alignment.LEADING)
        								.addComponent(jLabel3, Alignment.LEADING)
        								.addComponent(jLabel4, Alignment.LEADING)
        								.addComponent(jLabel5, Alignment.LEADING))
        							.addGap(0, 205, Short.MAX_VALUE))))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel7))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(ftCpfCadastro, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(ptSenhaCadastro, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(ptConSenhaCadastro, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(48)
        					.addComponent(lbConfirmacaoCadastro, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tfNomeCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cbTipoUsuarioCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(ftCpfCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(9)
        			.addComponent(jLabel5)
        			.addGap(2)
        			.addComponent(tfEmailCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel6)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(ptSenhaCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel7)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(ptConSenhaCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(29)
        			.addComponent(lbConfirmacaoCadastro, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addGap(41)
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btCancelarCadastro)
        				.addComponent(btSalvarCadastro))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5.setLayout(jPanel5Layout);

        jLabel15.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel15.setText("Pesquisar Usu\u00E1rio");

        jLabel16.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel16.setText("CPF");

        jLabel17.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel17.setText("Dados do usu\u00E1rio:");

        btPesquisarUsuario.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btPesquisarUsuario.setText("Pesquisar");

        btLimparPesqUsuario.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btLimparPesqUsuario.setText("Limpar");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeSettings.png")));
        
        tpnDadosUsuario = new JTextPane();
        tpnDadosUsuario.setEnabled(false);
        tpnDadosUsuario.setText("ID:\r\nNome:\r\nCpf:\r\nTipo:\r\nEmail:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(110)
        					.addComponent(jLabel15))
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(71)
        					.addComponent(btPesquisarUsuario)
        					.addGap(45)
        					.addComponent(btLimparPesqUsuario))
        				.addComponent(tfPesquisarCpf, 329, 329, 329)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(106)
        					.addComponent(jLabel13))
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(tpnDadosUsuario, GroupLayout.PREFERRED_SIZE, 307, GroupLayout.PREFERRED_SIZE))
        				.addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel15)
        			.addGap(18)
        			.addComponent(jLabel16)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(tfPesquisarCpf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(33)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btPesquisarUsuario)
        				.addComponent(btLimparPesqUsuario))
        			.addGap(53)
        			.addComponent(jLabel17)
        			.addGap(27)
        			.addComponent(tpnDadosUsuario, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel13)
        			.addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel6.setLayout(jPanel6Layout);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout gl_pnCadastro = new javax.swing.GroupLayout(pnCadastro);
        pnCadastro.setLayout(gl_pnCadastro);
        gl_pnCadastro.setHorizontalGroup(
            gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnCadastro.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gl_pnCadastro.setVerticalGroup(
            gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_pnCadastro.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gl_pnCadastro.createSequentialGroup()
                        .addGroup(gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastros", pnCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        pnVisualizacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReunioesPublica = new javax.swing.JTable();
        
                tbReunioesPublica.setModel(new DefaultTableModel(
                	new Object[][] {
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                		{null, null, null, null, null, null, null},
                	},
                	new String[] {
                		"Propriet\u00E1rio", "Local", "Sala", "Piso", "In\u00EDcio", "T\u00E9rmino", "Confirma\u00E7\u00E3o"
                	}
                ));
                tbReunioesPublica.getTableHeader().setReorderingAllowed(false);
                pnReuniao = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jPanel8 = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                btCancelarReuniao = new javax.swing.JButton();
                btCancelarReuniao.setAction(acLimparCadReuniao);
                btCadastrarReuniao = new javax.swing.JButton();
                btCadastrarReuniao.setAction(acCadReuniao);
                //jDateChooser1 = new com.toedter.calendar.JDateChooser();
                cbInicioReuniao = new javax.swing.JComboBox();
                cbInicioReuniao.setMaximumRowCount(14);
                jPanel9 = new javax.swing.JPanel();
                jLabel18 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                jLabel20 = new javax.swing.JLabel();
                tfNomeLocalPesq = new javax.swing.JTextField();
                cbEstado = new javax.swing.JComboBox();
                cbEstado.setMaximumRowCount(10);
                tfNomeSalaPesquisa = new javax.swing.JTextField();
                btPesqSala = new javax.swing.JButton();
                btPesqSala.setAction(acPesquisarSala);
                jLabel24 = new javax.swing.JLabel();
                jSeparator2 = new javax.swing.JSeparator();
                
                        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                        jLabel8.setText("Reservar Reunião");
                        
                                jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                jLabel9.setText("Data");
                                
                                        jLabel10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                        jLabel10.setText("In\u00EDcio");
                                        
                                                btCancelarReuniao.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                btCancelarReuniao.setText("Cancelar");
                                                
                                                        btCadastrarReuniao.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                        btCadastrarReuniao.setText("Confirmar");
                                                        
                                                                cbInicioReuniao.setFont(new Font("Times New Roman", Font.BOLD, 14)); // NOI18N
                                                                cbInicioReuniao.setModel(new DefaultComboBoxModel(new String[] {"07:00:00", "08:00:00", "09:00:00", "10:00:00", "11:00:00", "12:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00", "17:00:00", "18:00:00", "19:00:00", "20:00:00", "21:00:00"}));
                                                                
                                                                ftfDataReuniao = new JFormattedTextField();
                                                                
                                                                JLabel lblDurao = new JLabel();
                                                                lblDurao.setText("Termino");
                                                                lblDurao.setFont(new Font("Candara", Font.BOLD, 14));
                                                                
                                                                cbTerminoReuniao = new JComboBox();
                                                                cbTerminoReuniao.setMaximumRowCount(14);
                                                                cbTerminoReuniao.setModel(new DefaultComboBoxModel(new String[] {"08:00:00", "09:00:00", "10:00:00", "11:00:00", "12:00:00", "13:00:00", "14:00:00", "15:00:00", "16:00:00", "17::00:00", "18:00:00", "19:00:00", "20:00:00", "21:00:00", "22:00:00"}));
                                                                cbTerminoReuniao.setFont(new Font("Times New Roman", Font.BOLD, 14));
                                                                
                                                                JLabel lblIdLocal = new JLabel();
                                                                lblIdLocal.setText("ID Sala");
                                                                lblIdLocal.setFont(new Font("Candara", Font.BOLD, 14));
                                                                
                                                                tfIdSala = new JTextField();
                                                                tfIdSala.setColumns(10);
                                                                
                                                                JLabel lblSala = new JLabel();
                                                                lblSala.setText("Verifique seus dados antes de confirmar");
                                                                lblSala.setFont(new Font("Candara", Font.BOLD, 14));
                                                                cbAcessoReuniao = new javax.swing.JComboBox();
                                                                
                                                                        cbAcessoReuniao.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                        cbAcessoReuniao.setModel(new DefaultComboBoxModel(new String[] {"Publico", "Privado"}));
                                                                        jLabel23 = new javax.swing.JLabel();
                                                                        
                                                                                jLabel23.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                                jLabel23.setText("Acesso");
                                                                                
                                                                                JLabel label = new JLabel();
                                                                                label.setText("Nome do Local");
                                                                                label.setFont(new Font("Candara", Font.BOLD, 14));
                                                                                
                                                                                tfNomeLocalCadReuniao = new JTextField();
                                                                                
                                                                                        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                                                                                        jPanel8Layout.setHorizontalGroup(
                                                                                        	jPanel8Layout.createParallelGroup(Alignment.LEADING)
                                                                                        		.addGroup(jPanel8Layout.createSequentialGroup()
                                                                                        			.addContainerGap()
                                                                                        			.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
                                                                                        				.addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(lblIdLocal, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
                                                                                        					.addContainerGap(234, Short.MAX_VALUE))
                                                                                        				.addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                        					.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
                                                                                        						.addComponent(jLabel10)
                                                                                        						.addGroup(jPanel8Layout.createSequentialGroup()
                                                                                        							.addGap(97)
                                                                                        							.addComponent(jLabel8))
                                                                                        						.addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING, false)
                                                                                        							.addComponent(cbTerminoReuniao, Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                                                                        							.addComponent(cbInicioReuniao, Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                                        					.addContainerGap(89, Short.MAX_VALUE))
                                                                                        				.addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(lblDurao, GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                                                                        					.addGap(216))
                                                                                        				.addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(jLabel23)
                                                                                        					.addContainerGap(248, Short.MAX_VALUE))
                                                                                        				.addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(cbAcessoReuniao, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                                                                                        					.addContainerGap(183, Short.MAX_VALUE))
                                                                                        				.addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                        					.addGap(22)
                                                                                        					.addComponent(btCancelarReuniao)
                                                                                        					.addPreferredGap(ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                                                                        					.addComponent(btCadastrarReuniao)
                                                                                        					.addGap(41))
                                                                                        				.addGroup(Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(lblSala, GroupLayout.PREFERRED_SIZE, 260, GroupLayout.PREFERRED_SIZE)
                                                                                        					.addGap(18))
                                                                                        				.addGroup(jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(jLabel9)
                                                                                        					.addContainerGap(262, Short.MAX_VALUE))
                                                                                        				.addGroup(jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(label, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
                                                                                        					.addContainerGap(200, Short.MAX_VALUE))
                                                                                        				.addGroup(jPanel8Layout.createSequentialGroup()
                                                                                        					.addComponent(tfNomeLocalCadReuniao, GroupLayout.PREFERRED_SIZE, 271, GroupLayout.PREFERRED_SIZE)
                                                                                        					.addContainerGap(19, Short.MAX_VALUE))
                                                                                        				.addGroup(jPanel8Layout.createSequentialGroup()
                                                                                        					.addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING, false)
                                                                                        						.addComponent(tfIdSala, Alignment.LEADING)
                                                                                        						.addComponent(ftfDataReuniao, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                                                                        					.addContainerGap(150, Short.MAX_VALUE))))
                                                                                        );
                                                                                        jPanel8Layout.setVerticalGroup(
                                                                                        	jPanel8Layout.createParallelGroup(Alignment.LEADING)
                                                                                        		.addGroup(jPanel8Layout.createSequentialGroup()
                                                                                        			.addContainerGap()
                                                                                        			.addComponent(jLabel8)
                                                                                        			.addGap(11)
                                                                                        			.addComponent(label, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addGap(4)
                                                                                        			.addComponent(tfNomeLocalCadReuniao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addGap(18)
                                                                                        			.addComponent(jLabel10)
                                                                                        			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                                        			.addComponent(cbInicioReuniao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                                        			.addComponent(lblDurao, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addComponent(cbTerminoReuniao, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addComponent(lblIdLocal, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addComponent(tfIdSala, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addComponent(jLabel23)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addComponent(cbAcessoReuniao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addComponent(jLabel9)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                        			.addComponent(ftfDataReuniao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                                                                        			.addComponent(lblSala, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                                                                                        			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                                        			.addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE)
                                                                                        				.addComponent(btCancelarReuniao)
                                                                                        				.addComponent(btCadastrarReuniao))
                                                                                        			.addGap(25))
                                                                                        );
                                                                                        jPanel8.setLayout(jPanel8Layout);
                                                                                        
                                                                                                jLabel18.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                                                jLabel18.setText("Pesquisar Sala");
                                                                                                
                                                                                                        jLabel19.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                                                        jLabel19.setText("Nome do Local");
                                                                                                        
                                                                                                                jLabel20.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                                                                jLabel20.setText("Cidade");
                                                                                                                
                                                                                                                        cbEstado.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                                                                        cbEstado.setModel(new DefaultComboBoxModel(new String[] {"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"}));
                                                                                                                        
                                                                                                                                btPesqSala.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                                                                                btPesqSala.setText("Pesquisar");
                                                                                                                                btPesqSala.setMargin(new java.awt.Insets(5, 14, 2, 14));
                                                                                                                                
                                                                                                                                        jLabel24.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                                                                                                                                        jLabel24.setText("Nome da Sala");
                                                                                                                                        
                                                                                                                                        btLimparPesqSala = new JButton();
                                                                                                                                        btLimparPesqSala.setAction(acLimparPesqSala);
                                                                                                                                        btLimparPesqSala.setText("Limpar");
                                                                                                                                        btLimparPesqSala.setMargin(new Insets(5, 14, 2, 14));
                                                                                                                                        btLimparPesqSala.setFont(new Font("Candara", Font.BOLD, 14));
                                                                                                                                        
                                                                                                                                        lblDadosDoLocal = new JLabel();
                                                                                                                                        lblDadosDoLocal.setText("Dados da Sala");
                                                                                                                                        lblDadosDoLocal.setFont(new Font("Candara", Font.BOLD, 14));
                                                                                                                                        
                                                                                                                                        tfCidadePesquisa = new JTextField();
                                                                                                                                        
                                                                                                                                        JLabel lblEstado = new JLabel();
                                                                                                                                        lblEstado.setText("Estado");
                                                                                                                                        lblEstado.setFont(new Font("Candara", Font.BOLD, 14));
                                                                                                                                        
                                                                                                                                        tpDadosPesqSala = new JTextPane();
                                                                                                                                        tpDadosPesqSala.setEnabled(false);
                                                                                                                                        tpDadosPesqSala.setText("Nome:\r\nID Sala:\r\nPiso:\r\nNumero:\r\nID Local:");
                                                                                                                                        
                                                                                                                                        lblNewLabel = new JLabel("*Dados em branco, quer dizer sem registro ");
                                                                                                                                        lblNewLabel.setFont(new Font("SansSerif", Font.BOLD, 11));
                                                                                                                                        
                                                                                                                                                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                                                                                                                                                jPanel9Layout.setHorizontalGroup(
                                                                                                                                                	jPanel9Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                		.addGroup(jPanel9Layout.createSequentialGroup()
                                                                                                                                                			.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                				.addComponent(jLabel19)
                                                                                                                                                				.addGroup(jPanel9Layout.createSequentialGroup()
                                                                                                                                                					.addGap(109)
                                                                                                                                                					.addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                				.addComponent(jLabel20, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                				.addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                				.addComponent(lblEstado, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                				.addComponent(cbEstado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                				.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING, false)
                                                                                                                                                					.addComponent(tfNomeSalaPesquisa)
                                                                                                                                                					.addComponent(tfNomeLocalPesq)
                                                                                                                                                					.addComponent(tfCidadePesquisa)
                                                                                                                                                					.addGroup(jPanel9Layout.createSequentialGroup()
                                                                                                                                                						.addGap(38)
                                                                                                                                                						.addComponent(btPesqSala)
                                                                                                                                                						.addGap(33)
                                                                                                                                                						.addComponent(btLimparPesqSala, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE))))
                                                                                                                                                			.addContainerGap())
                                                                                                                                                		.addGroup(jPanel9Layout.createSequentialGroup()
                                                                                                                                                			.addContainerGap(89, Short.MAX_VALUE)
                                                                                                                                                			.addComponent(lblDadosDoLocal, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addGap(79))
                                                                                                                                                		.addGroup(jPanel9Layout.createSequentialGroup()
                                                                                                                                                			.addContainerGap()
                                                                                                                                                			.addComponent(tpDadosPesqSala, GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                                                                                                                                			.addContainerGap())
                                                                                                                                                		.addGroup(Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                                                                                                                                			.addContainerGap()
                                                                                                                                                			.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                                                                                                                                			.addContainerGap())
                                                                                                                                                );
                                                                                                                                                jPanel9Layout.setVerticalGroup(
                                                                                                                                                	jPanel9Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                		.addGroup(jPanel9Layout.createSequentialGroup()
                                                                                                                                                			.addContainerGap()
                                                                                                                                                			.addComponent(jLabel18)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                                                                                                			.addComponent(jLabel19)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(tfNomeLocalPesq, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(jLabel20)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(tfCidadePesquisa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(jLabel24)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(tfNomeSalaPesquisa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(lblEstado, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(cbEstado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addGap(18)
                                                                                                                                                			.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                				.addComponent(btLimparPesqSala, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                				.addComponent(btPesqSala, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                                                                                                                                			.addComponent(lblDadosDoLocal, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                			.addComponent(tpDadosPesqSala, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                			.addPreferredGap(ComponentPlacement.UNRELATED)
                                                                                                                                                			.addComponent(lblNewLabel)
                                                                                                                                                			.addGap(29))
                                                                                                                                                );
                                                                                                                                                jPanel9.setLayout(jPanel9Layout);
                                                                                                                                                
                                                                                                                                                        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
                                                                                                                                                        
                                                                                                                                                                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                                                                                                                                                                jPanel7Layout.setHorizontalGroup(
                                                                                                                                                                	jPanel7Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                		.addGroup(jPanel7Layout.createSequentialGroup()
                                                                                                                                                                			.addContainerGap()
                                                                                                                                                                			.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                			.addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 12, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                			.addPreferredGap(ComponentPlacement.RELATED)
                                                                                                                                                                			.addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                			.addContainerGap(19, Short.MAX_VALUE))
                                                                                                                                                                );
                                                                                                                                                                jPanel7Layout.setVerticalGroup(
                                                                                                                                                                	jPanel7Layout.createParallelGroup(Alignment.TRAILING)
                                                                                                                                                                		.addGroup(jPanel7Layout.createSequentialGroup()
                                                                                                                                                                			.addContainerGap()
                                                                                                                                                                			.addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
                                                                                                                                                                				.addComponent(jPanel9, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                                                                				.addComponent(jPanel8, GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                                                                                                                                                                			.addContainerGap())
                                                                                                                                                                		.addComponent(jSeparator2, GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                                                                                                                                                                );
                                                                                                                                                                jPanel7.setLayout(jPanel7Layout);
                                                                                                                                                                
                                                                                                                                                                        javax.swing.GroupLayout gl_pnReuniao = new javax.swing.GroupLayout(pnReuniao);
                                                                                                                                                                        pnReuniao.setLayout(gl_pnReuniao);
                                                                                                                                                                        gl_pnReuniao.setHorizontalGroup(
                                                                                                                                                                            gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                            .addGap(0, 693, Short.MAX_VALUE)
                                                                                                                                                                            .addGroup(gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addGroup(gl_pnReuniao.createSequentialGroup()
                                                                                                                                                                                    .addGap(0, 14, Short.MAX_VALUE)
                                                                                                                                                                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                    .addGap(0, 14, Short.MAX_VALUE)))
                                                                                                                                                                        );
                                                                                                                                                                        gl_pnReuniao.setVerticalGroup(
                                                                                                                                                                            gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                            .addGap(0, 531, Short.MAX_VALUE)
                                                                                                                                                                            .addGroup(gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addGroup(gl_pnReuniao.createSequentialGroup()
                                                                                                                                                                                    .addGap(0, 43, Short.MAX_VALUE)
                                                                                                                                                                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                    .addGap(0, 44, Short.MAX_VALUE)))
                                                                                                                                                                        );
                                                                                                                                                                        
                                                                                                                                                                                jTabbedPane1.addTab("Reuniões", pnReuniao);
                jScrollPane1.setViewportView(tbReunioesPublica);
                
                JLabel lblReuniesPblicas = new JLabel("Reuni\u00F5es P\u00FAblicas");
                lblReuniesPblicas.setFont(new Font("Times New Roman", Font.BOLD, 14));
                
                JScrollPane scrollPane = new JScrollPane();
                
                JLabel lblReuniesConvidadas = new JLabel("Reuni\u00F5es Convidadas");
                lblReuniesConvidadas.setFont(new Font("Times New Roman", Font.BOLD, 14));
                        
                        JButton btMostrar = new JButton("Mostrar");
                        btMostrar.setBackground(UIManager.getColor("Button.background"));
                        btMostrar.setForeground(Color.BLACK);
                        btMostrar.setAction(acMostrarRePublica);
                        
                        btnMostrarReunisConvidadas = new JButton("Mostrar Reuni\u00F5s Convidadas");
                        btnMostrarReunisConvidadas.setForeground(Color.BLACK);
                        btnMostrarReunisConvidadas.setBackground(UIManager.getColor("Button.background"));
                
                        javax.swing.GroupLayout gl_pnVisualizacao = new javax.swing.GroupLayout(pnVisualizacao);
                        gl_pnVisualizacao.setHorizontalGroup(
                        	gl_pnVisualizacao.createParallelGroup(Alignment.TRAILING)
                        		.addGroup(gl_pnVisualizacao.createSequentialGroup()
                        			.addContainerGap()
                        			.addGroup(gl_pnVisualizacao.createParallelGroup(Alignment.LEADING)
                        				.addGroup(gl_pnVisualizacao.createParallelGroup(Alignment.LEADING)
                        					.addGroup(Alignment.TRAILING, gl_pnVisualizacao.createSequentialGroup()
                        						.addGroup(gl_pnVisualizacao.createParallelGroup(Alignment.TRAILING)
                        							.addComponent(scrollPane, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                        							.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
                        						.addContainerGap())
                        					.addGroup(gl_pnVisualizacao.createSequentialGroup()
                        						.addComponent(btMostrar, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                        						.addGap(131)
                        						.addComponent(lblReuniesConvidadas, GroupLayout.PREFERRED_SIZE, 181, GroupLayout.PREFERRED_SIZE)
                        						.addContainerGap())
                        					.addGroup(gl_pnVisualizacao.createSequentialGroup()
                        						.addComponent(btnMostrarReunisConvidadas, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
                        						.addContainerGap()))
                        				.addGroup(Alignment.TRAILING, gl_pnVisualizacao.createSequentialGroup()
                        					.addComponent(lblReuniesPblicas, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
                        					.addGap(230))))
                        );
                        gl_pnVisualizacao.setVerticalGroup(
                        	gl_pnVisualizacao.createParallelGroup(Alignment.LEADING)
                        		.addGroup(gl_pnVisualizacao.createSequentialGroup()
                        			.addGap(13)
                        			.addComponent(lblReuniesPblicas)
                        			.addGap(18)
                        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
                        			.addGap(18)
                        			.addGroup(gl_pnVisualizacao.createParallelGroup(Alignment.LEADING)
                        				.addComponent(lblReuniesConvidadas, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                        				.addComponent(btMostrar))
                        			.addGap(18)
                        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
                        			.addGap(18)
                        			.addComponent(btnMostrarReunisConvidadas)
                        			.addContainerGap(28, Short.MAX_VALUE))
                        );
                        
                        tbReunioesConvidadas = new JTable();
                        tbReunioesConvidadas.setModel(new DefaultTableModel(
                        	new Object[][] {
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        		{null, null, null, null, null, null, null},
                        	},
                        	new String[] {
                        		"Propriet\u00E1rio", "Local", "Sala", "Piso", "In\u00EDcio", "T\u00E9rmino", "Confirma\u00E7\u00E3o"
                        	}
                        ));
                        scrollPane.setViewportView(tbReunioesConvidadas);
                        pnVisualizacao.setLayout(gl_pnVisualizacao);
                        
                                jTabbedPane1.addTab("Vizualizar Reuniões", pnVisualizacao);
        
        JPanel pnConfirmacao_Pariticipacao = new JPanel();
        jTabbedPane1.addTab("Confrima\u00E7\u00E3o & Participa\u00E7\u00E3o", null, pnConfirmacao_Pariticipacao, null);
        pnConfirmacao_Pariticipacao.setLayout(null);
        
        JSeparator separator = new JSeparator();
        separator.setOrientation(SwingConstants.VERTICAL);
        separator.setBounds(346, 11, 8, 568);
        pnConfirmacao_Pariticipacao.add(separator);
        
        JPanel panel = new JPanel();
        panel.setBounds(10, 11, 326, 568);
        pnConfirmacao_Pariticipacao.add(panel);
        panel.setLayout(null);
        
        JLabel lblConfirmarParticipao = new JLabel("Confirmar Participa\u00E7\u00E3o");
        lblConfirmarParticipao.setFont(new Font("Sitka Small", Font.BOLD, 12));
        lblConfirmarParticipao.setBounds(74, 11, 195, 21);
        panel.add(lblConfirmarParticipao);
        
        JPanel panel_1 = new JPanel();
        panel_1.setBounds(369, 11, 326, 568);
        pnConfirmacao_Pariticipacao.add(panel_1);
        panel_1.setLayout(null);
        
        JLabel lblAdicionarParticipante = new JLabel("Adicionar Participante");
        lblAdicionarParticipante.setFont(new Font("Sitka Small", Font.BOLD, 12));
        lblAdicionarParticipante.setBounds(68, 11, 195, 21);
        panel_1.add(lblAdicionarParticipante);
        
        pnAta = new JPanel();
        jTabbedPane1.addTab("Atas", null, pnAta, null);
        
        pnPlanoDeAcao = new JPanel();
        jTabbedPane1.addTab("Plano de Ação", null, pnPlanoDeAcao, null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioComum().setVisible(true);
            }
        });
    }
    
    public void receberUsuario(Comum userComum) {
		System.out.println("Recebendo o objeto usuario!");
		usuario = userComum;	
	}
	
	public void receberConeccao(Connection con) {
		conect = con;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarCadastro;
    private javax.swing.JButton btSalvarCadastro;
    private javax.swing.JButton btPesquisarUsuario;
    private javax.swing.JButton btCancelarReuniao;
    private javax.swing.JButton btCadastrarReuniao;
    private javax.swing.JComboBox cbAcessoReuniao;
    private javax.swing.JComboBox cbInicioReuniao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnCadastro;
    private javax.swing.JPanel pnReuniao;
    private javax.swing.JPanel pnVisualizacao;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbReunioesPublica;    
    private javax.swing.JTextField tfPesquisarCpf;
    private JPanel pnAta;
    private JPanel pnPlanoDeAcao;
    private JTextField tfIdSala;
    private JButton btLimparPesqSala;
    private JLabel lblDadosDoLocal;
    private JTable tbReunioesConvidadas;
    private JLabel lblNewLabel;
    private JTextField tfNomeLocalCadReuniao;
    
    // Definindo açoes
    private final Action acCadUsuario = new SwingAction();
    private final Action acPesqUsuario = new SwingAction_2();
    private final Action acLimpPesqUsuario = new SwingAction_1();
    private final Action acLimparCadUsuario = new SwingAction_3();
    private final Action acPesquisarSala = new SwingAction_4();
    private final Action acLimparPesqSala = new SwingAction_5();
    private final Action acCadReuniao = new SwingAction_6();
    private final Action acLimparCadReuniao = new SwingAction_7();
    private final Action acMostrarRePublica = new SwingAction_8();
    private JButton btnMostrarReunisConvidadas;
   
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "CadastrarUsuario");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		
		// --------------- Açoes da Aba de Cadastro e Pesquisa de Usuario ----------------------
		
		public void actionPerformed(ActionEvent e) {
			String nome, cpf, email, senha, confirmarSenha, tipoUsuario;
			nome = tfNomeCadastro.getText();
			cpf = ftCpfCadastro.getText();
			email = tfEmailCadastro.getText();
			senha = ptSenhaCadastro.getText();
			confirmarSenha = ptConSenhaCadastro.getText();
			tipoUsuario = ((String) cbTipoUsuarioCadastro.getSelectedItem()); // casting de Object para String
			System.out.println((String) cbTipoUsuarioCadastro.getSelectedItem()); // esse mesmo!
			System.out.println("Tipo de usuario: "+tipoUsuario);
			if(senha.equals(confirmarSenha)) {
				usuario.cadastrarUsuario(conect, ps, rt, nome, cpf, confirmarSenha, email, tipoUsuario);
				lbConfirmacaoCadastro.setText("As senhas são iguais");
				JOptionPane.showMessageDialog(rootPane, "Usuario cadastrado");
			}else {
				lbConfirmacaoCadastro.setText("Senhas diferentes, digite as novamente!");
			}
			System.out.println("Dados:");
			System.out.println("Nome: "+nome+", Cpf: "+cpf+", Email"+email+"\nSehna: "+senha+", Confirmar Senha"+confirmarSenha);
			
		}
	}
	
	private class SwingAction_2 extends AbstractAction {
		public SwingAction_2() {
			putValue(NAME, "PesquisarUsuario");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
			// Implementar Funcionalidade
			String cpf = tfPesquisarCpf.getText();
			tfPesquisarCpf.setText(cpf);
			System.out.println(cpf);// peguei o cpf!
			user = usuario.pesquisarUsuario(cpf, conect, rt);
			if(user == null) {
				System.out.println("Usuario não existe");
			}else{
				System.out.println(user.toString());// aqui nao esta o toString!!
				tpnDadosUsuario.setText("ID: "+user.getIdUser()+"\nNome: "+user.getNome()+
						"\nCpf: "+user.getCpf()+"\nTipo: "+user.getTipo()+"\nE-mail: "+user.getEmail());
			}
			//btPesquisarUsuario.setEnabled(false);
		}	
	}
	
	private class SwingAction_1 extends AbstractAction {
		public SwingAction_1() {
			putValue(NAME, "LimparPesquisarUsuario");
			putValue(SHORT_DESCRIPTION, "Limpar campo de pesquisa");
		}
		public void actionPerformed(ActionEvent e) { // ESTOU ACHANDO QUE O PROBLEMA É DO ESCOPO DE ACTION!
			// Quando clico em limpar, não consigo mais pesquisar um novo usuario!!
			//user = null;
			tfPesquisarCpf.setText(""); // O Problema esta aqui!!!! como resolver isso?? 
			//btPesquisarUsuario.setEnabled(true);
			System.out.println("Cliquei no botão Limpar!");
		}
	}
	private class SwingAction_3 extends AbstractAction {
		public SwingAction_3() {
			putValue(NAME, "SwingAction_3");
			putValue(SHORT_DESCRIPTION, "Limpar campos de cadastro");
		}
		public void actionPerformed(ActionEvent e) {
			tfNomeCadastro.setText("");
			ftCpfCadastro.setText("");
			tfEmailCadastro.setText("");
			ptSenhaCadastro.setText("");
			ptConSenhaCadastro.setText("");
		}
	}
	
	// --------------- Açoes da Aba de Reuniao ----------------------
	
	
	private class SwingAction_4 extends AbstractAction {
		public SwingAction_4() {
			putValue(NAME, "Pesquisar Sala");
			putValue(SHORT_DESCRIPTION, "");
		}
		public void actionPerformed(ActionEvent e) {
			Sala sala = null;
			String nomeLocal, nomeSala, cidade, estado;
			nomeLocal = tfNomeLocalPesq.getText();
			nomeSala = tfNomeSalaPesquisa.getText();
			cidade = tfCidadePesquisa.getText();
			estado = ((String) cbEstado.getSelectedItem());
			System.out.println("Local: "+nomeLocal+", Sala: "+nomeSala+", Cidade: "+cidade+", Estado: "+estado);
			
			int idSala = Validacao.verificarSala(conect, rt, nomeLocal, nomeSala, cidade);
			if(idSala != 0) {
				sala = MetodosEstaticos.getSala(idSala, conect, rt);
				System.out.println(sala.toString());
				tpDadosPesqSala.setText("Nome: "+sala.getNomeSala()+"\nID Sala: "+sala.getIdSala()+
										"\nPiso: "+sala.getPiso()+"\nNúmero: "+"\nID Local: "+sala.getIdLocal());
			}else if (idSala == 0){
				System.out.println("Nao exista sala com esses dados!");
				JOptionPane.showMessageDialog(rootPane, "Sala não encontrada!");
			}
			btPesqSala.setEnabled(false);
		}
	}
	private class SwingAction_5 extends AbstractAction {
		public SwingAction_5() {
			putValue(NAME, "Limpar Pesquisa");
			putValue(SHORT_DESCRIPTION, "");
		}
		public void actionPerformed(ActionEvent e) {
			tfNomeLocalPesq.setText("");
			tfNomeSalaPesquisa.setText("");
			tfCidadePesquisa.setText("");
			tpDadosPesqSala.setText("Nome: "+"\nID Sala: "+"\nPiso: "+"\nNúmero: "+"\nID Local: ");
			btPesqSala.setEnabled(true);
		}
	}
	private class SwingAction_6 extends AbstractAction {
		public SwingAction_6() {
			putValue(NAME, "SwingAction_6");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
			String local, data, horaInicial, horaFinal, acesso;
			int idSala = Integer.parseInt(tfIdSala.getText());
			local = tfNomeLocalCadReuniao.getText();
			horaInicial = ((String) cbInicioReuniao.getSelectedItem());
			horaFinal = ((String) cbTerminoReuniao.getSelectedItem());
			acesso = ((String)cbAcessoReuniao.getSelectedItem());
			data = ftfDataReuniao.getText();
			System.out.println("ID SALA:"+idSala+" /Local: "+local+"/Horario Inicial: "+horaInicial+"\nHorario Final: "+horaFinal+
								"/Acesso:"+acesso+" /Data: "+data);
			int idReuniao = Validacao.verificarReuniao(idSala, data, horaInicial, conect, rt);
			// FUNCIONANDO!!
		}
	}
	private class SwingAction_7 extends AbstractAction {
		public SwingAction_7() {
			putValue(NAME, "SwingAction_7");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
		}
	}
	private class SwingAction_8 extends AbstractAction {
		public SwingAction_8() {
			putValue(NAME, "Mostrar Reunioes Publicas");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
		}
	}
}
