package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import modelo.Comum;
import modelo.Coordenador;
import modelo.Gestor;
import modelo.Usuario;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import controle.MetodosEstaticos;

import javax.swing.JRadioButton;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;

/**
 *
 * @author Carlos Jr
 */
public class UsuarioCoordenador extends javax.swing.JFrame {
	
	private DefaultTableModel modeloReunioesConf;

	// Instacias uteis
	boolean setViewTableConf = true; // usar para iniciar a tabela de reunioes confirmadas!
	Usuario usuario = null;
	Connection conect = null;
	ResultSet rt = null;
	Coordenador coordenador = null;
	Statement st = null;
 	PreparedStatement ps = null;
 	Object[] linhasTbReunioesConf =  new Object[7];;
	
	public void receberUsuario(Coordenador userCoordenador) {
			System.out.println("Recebendo o objeto usuario!");
			coordenador = userCoordenador;	
		}
	
	public void receberConeccao(Connection con) {
			conect = con;
		}
	
    public UsuarioCoordenador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnAgReunioes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton3.setAction(acMostrarReConfirmadas);
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReunioesConf = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        pnReunioes = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jEditorPane1.setEnabled(false);
        pnAtas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnRealocacoes = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnRealcSala = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        pnRealcPartList = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jTextField12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("e-Meeting - Usuário Coordenador");

        jTabbedPane1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setText("Reuniões em que você foi adicionado");

        jTable1.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Período", "Ata", "Nome do local", "Sala", "Cidade", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(28);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(28);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable1.getColumnModel().getColumn(1).setMinWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(2).setMinWidth(55);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(55);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(55);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(70);
        }

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reunioes.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText("Palavras-chave para pesquisar");

        jButton3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton3.setText("Pesquisar");

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setText("ID da reunião");

        jButton4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton4.setText("Negar");

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setText("Confirmar ou Negar presença na reunião");

        jButton5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton5.setText("Confirmar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setText("Reuniões em que você confirmou presença");

        tbReunioesConf.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N
        Object[] colunaTbReunioesConf = {"ID", "Data", "Periodo", "Local", "Cidade", "Sala", "Piso"};
        modeloReunioesConf = new DefaultTableModel(0,1);
        modeloReunioesConf.setColumnIdentifiers(colunaTbReunioesConf);        	
        tbReunioesConf.setModel(modeloReunioesConf);
        
        /*tbReunioesConf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Período", "Ata", "Nome do local", "Sala", "Cidade", "Estado"
            }
        ) */
        /*{
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });*/
        //tbReunioesConf.getTableHeader().setReorderingAllowed(false);
        
        jScrollPane2.setViewportView(tbReunioesConf);
        /*if (tbReunioesConf.getColumnModel().getColumnCount() > 0) {
            tbReunioesConf.getColumnModel().getColumn(0).setMinWidth(28);
            tbReunioesConf.getColumnModel().getColumn(0).setPreferredWidth(28);
            tbReunioesConf.getColumnModel().getColumn(0).setMaxWidth(35);
            tbReunioesConf.getColumnModel().getColumn(1).setMinWidth(50);
            tbReunioesConf.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbReunioesConf.getColumnModel().getColumn(1).setMaxWidth(50);
            tbReunioesConf.getColumnModel().getColumn(2).setMinWidth(55);
            tbReunioesConf.getColumnModel().getColumn(2).setPreferredWidth(55);
            tbReunioesConf.getColumnModel().getColumn(2).setMaxWidth(55);
            tbReunioesConf.getColumnModel().getColumn(6).setResizable(false);
            tbReunioesConf.getColumnModel().getColumn(6).setHeaderValue("Cidade");
            tbReunioesConf.getColumnModel().getColumn(7).setResizable(false);
            tbReunioesConf.getColumnModel().getColumn(7).setPreferredWidth(70);
            tbReunioesConf.getColumnModel().getColumn(7).setHeaderValue("Estado");
        }*/
        // Por que nao esta FUNCIONANDO ??? TENTAR COLOCAR DENTRO DE UM ACAO!
        //if(setViewTableConf) {
        	// entrar com o codigo de visualização da tabela
        	/*try { 
    			ps = conect.prepareStatement("SELECT PERIODO, DATA_REUNIAO, NOME_SALA, PISO, NOME_LOCAL, CIDADE, PARTICIPACAO, IDREUNIAO "  
    					+"FROM SALA "
    					+"INNER JOIN LOCAL "
    					+"ON IDLOCAL = ID_LOCAL "
    					+"INNER JOIN REUNIAO "
    					+"ON IDSALA = ID_SALA "
    					+"INNER JOIN USUARIO__REUNIAO "
    					+"ON ID_REUNIAO = IDREUNIAO "
    					+"WHERE PARTICIPACAO = ? AND ID_USUARIO = ? ");
    			ps.setString(1, "SIM");
    			ps.setInt(2, usuario.getIdUser());
    			rt = ps.executeQuery();
    			while(rt.next()) { // verificar a ordem!!
    				//String local, sala, nome, periodo, confirmacao, piso , data;
    				linhasTbReunioesConf[0] = rt.getString("IDREUNIAO");
    				linhasTbReunioesConf[1] = rt.getString("DATA_REUNIAO");
    				linhasTbReunioesConf[2] = rt.getString("PERIODO");
    				linhasTbReunioesConf[3] = rt.getString("NOME_LOCAL");
    				linhasTbReunioesConf[4] = rt.getString("CIDADE");
    				linhasTbReunioesConf[5] = rt.getString("NOME_SALA");
    				linhasTbReunioesConf[6] = rt.getString("PISO");
    				modeloReunioesConf.addRow(linhasTbReunioesConf);
    		}
    		
    	} catch (SQLException eVisualizarReConf) {
    		eVisualizarReConf.printStackTrace();
    	 }
       }*/
        
        javax.swing.GroupLayout gl_pnAgReunioes = new javax.swing.GroupLayout(pnAgReunioes);
        pnAgReunioes.setLayout(gl_pnAgReunioes);
        gl_pnAgReunioes.setHorizontalGroup(
            gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnAgReunioes.createSequentialGroup()
                .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_pnAgReunioes.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_pnAgReunioes.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButton3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gl_pnAgReunioes.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel6)
                        .addGap(0, 200, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gl_pnAgReunioes.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gl_pnAgReunioes.createSequentialGroup()
                                .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(gl_pnAgReunioes.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gl_pnAgReunioes.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        gl_pnAgReunioes.setVerticalGroup(
            gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnAgReunioes.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_pnAgReunioes.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_pnAgReunioes.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(gl_pnAgReunioes.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(gl_pnAgReunioes.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Agenda de reuniões", pnAgReunioes);

        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel8.setText("Pesquisar sala");

        jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel9.setText("Data");

        jLabel10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel10.setText("ID Sala");

        jLabel11.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel11.setText("Período");

        jLabel12.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel12.setText("Acesso");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Privado" }));

        jLabel13.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel13.setText("Verifique os dados antes de confirmar");

        jButton1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton1.setText("Cancelar");

        jButton2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton2.setText("Confirmar");

        jLabel14.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel14.setText("Reservar Reunião");

        jLabel15.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel15.setText("Nome do local");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel16.setText("Cidade");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel17.setText("Nome da sala");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel18.setText("Estado");

        jComboBox4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jButton6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton6.setText("Limpar");

        jButton7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton7.setText("Pesquisar");

        jLabel19.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel19.setText("Dados da sala");

        jScrollPane4.setViewportView(jEditorPane1);
        
        JRadioButton rdbtnManha = new JRadioButton("Manha");
        
        JRadioButton rdbtnTarde = new JRadioButton("Tarde");
        
        JRadioButton rdbtnNoite = new JRadioButton("Noite");

        javax.swing.GroupLayout gl_pnReunioes = new javax.swing.GroupLayout(pnReunioes);
        gl_pnReunioes.setHorizontalGroup(
        	gl_pnReunioes.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pnReunioes.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_pnReunioes.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_pnReunioes.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel11)
        					.addGroup(gl_pnReunioes.createSequentialGroup()
        						.addGap(104)
        						.addComponent(jLabel14))
        					.addGroup(gl_pnReunioes.createSequentialGroup()
        						.addGap(21)
        						.addGroup(gl_pnReunioes.createParallelGroup(Alignment.LEADING)
        							.addComponent(jLabel13)
        							.addGroup(gl_pnReunioes.createSequentialGroup()
        								.addComponent(jButton1)
        								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jButton2)))))
        				.addGroup(gl_pnReunioes.createSequentialGroup()
        					.addComponent(rdbtnManha)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(rdbtnTarde)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(rdbtnNoite))
        				.addComponent(jLabel9)
        				.addComponent(jLabel10)
        				.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel12)
        				.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
        			.addGroup(gl_pnReunioes.createParallelGroup(Alignment.TRAILING)
        				.addGroup(gl_pnReunioes.createParallelGroup(Alignment.TRAILING, false)
        					.addGroup(gl_pnReunioes.createSequentialGroup()
        						.addGroup(gl_pnReunioes.createParallelGroup(Alignment.TRAILING)
        							.addGroup(gl_pnReunioes.createParallelGroup(Alignment.TRAILING)
        								.addGroup(gl_pnReunioes.createSequentialGroup()
        									.addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        									.addGap(272))
        								.addGroup(gl_pnReunioes.createSequentialGroup()
        									.addPreferredGap(ComponentPlacement.RELATED, 62, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jButton7)
        									.addGap(94)
        									.addComponent(jButton6))
        								.addComponent(jLabel15)
        								.addComponent(jTextField5)
        								.addComponent(jTextField6)
        								.addComponent(jLabel17)
        								.addComponent(jTextField7)
        								.addComponent(jLabel18)
        								.addComponent(jLabel16))
        							.addGroup(gl_pnReunioes.createSequentialGroup()
        								.addComponent(jLabel8)
        								.addGap(121)))
        						.addContainerGap())
        					.addGroup(gl_pnReunioes.createSequentialGroup()
        						.addComponent(jLabel19)
        						.addGap(142)))
        				.addGroup(gl_pnReunioes.createSequentialGroup()
        					.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 272, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        gl_pnReunioes.setVerticalGroup(
        	gl_pnReunioes.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pnReunioes.createSequentialGroup()
        			.addGap(26)
        			.addGroup(gl_pnReunioes.createParallelGroup(Alignment.TRAILING)
        				.addGroup(gl_pnReunioes.createSequentialGroup()
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jLabel11)
        					.addGap(232))
        				.addGroup(gl_pnReunioes.createSequentialGroup()
        					.addGroup(gl_pnReunioes.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_pnReunioes.createSequentialGroup()
        							.addGroup(gl_pnReunioes.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel8)
        								.addComponent(jLabel14))
        							.addGap(93)
        							.addGroup(gl_pnReunioes.createParallelGroup(Alignment.BASELINE)
        								.addComponent(rdbtnManha)
        								.addComponent(rdbtnTarde)
        								.addComponent(rdbtnNoite))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jLabel10)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jLabel12)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(29)
        							.addComponent(jLabel9))
        						.addGroup(gl_pnReunioes.createSequentialGroup()
        							.addGap(29)
        							.addComponent(jLabel15)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jLabel16)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jLabel17)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jLabel18)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(15)
        							.addGroup(gl_pnReunioes.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jButton6)
        								.addComponent(jButton7))))
        					.addGap(18)
        					.addComponent(jLabel19)))
        			.addGroup(gl_pnReunioes.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_pnReunioes.createSequentialGroup()
        					.addGap(47)
        					.addComponent(jLabel13)
        					.addGap(18)
        					.addGroup(gl_pnReunioes.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jButton1)
        						.addComponent(jButton2)))
        				.addGroup(gl_pnReunioes.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(48, Short.MAX_VALUE))
        );
        pnReunioes.setLayout(gl_pnReunioes);

        jTabbedPane1.addTab("Criar reuniões", pnReunioes);

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setText("Reuniões em que você confirmou presença");

        jTable3.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Período", "Ata", "Nome do local", "Sala"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(28);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(28);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable3.getColumnModel().getColumn(1).setMinWidth(50);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable3.getColumnModel().getColumn(1).setMaxWidth(50);
            jTable3.getColumnModel().getColumn(2).setMinWidth(55);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(55);
            jTable3.getColumnModel().getColumn(2).setMaxWidth(55);
        }

        jLabel20.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel20.setText("Editar ata da reunião");

        jLabel21.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel21.setText("ID da reunião");

        jButton8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton8.setText("Alterar ata");

        jScrollPane5.setViewportView(jTextPane1);

        javax.swing.GroupLayout gl_pnAtas = new javax.swing.GroupLayout(pnAtas);
        pnAtas.setLayout(gl_pnAtas);
        gl_pnAtas.setHorizontalGroup(
            gl_pnAtas.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnAtas.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_pnAtas.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gl_pnAtas.createSequentialGroup()
                        .addGroup(gl_pnAtas.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gl_pnAtas.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel7))
                            .addComponent(jLabel20)
                            .addComponent(jButton8)
                            .addGroup(gl_pnAtas.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(gl_pnAtas.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        gl_pnAtas.setVerticalGroup(
            gl_pnAtas.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnAtas.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gl_pnAtas.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Atas", pnAtas);

        jTabbedPane2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel22.setText("Reuniões Marcadas");

        jButton9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton9.setText("Realocar reunião");

        jTable5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Proprietário", "Local", "Sala", "Piso", "Início", "Término", "Confirmação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(jTable5);
        if (jTable5.getColumnModel().getColumnCount() > 0) {
            jTable5.getColumnModel().getColumn(0).setMinWidth(28);
            jTable5.getColumnModel().getColumn(0).setPreferredWidth(28);
            jTable5.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable5.getColumnModel().getColumn(1).setHeaderValue("Proprietário");
            jTable5.getColumnModel().getColumn(2).setResizable(false);
            jTable5.getColumnModel().getColumn(2).setHeaderValue("Local");
            jTable5.getColumnModel().getColumn(3).setHeaderValue("Sala");
            jTable5.getColumnModel().getColumn(4).setHeaderValue("Piso");
            jTable5.getColumnModel().getColumn(5).setHeaderValue("Início");
            jTable5.getColumnModel().getColumn(6).setHeaderValue("Término");
            jTable5.getColumnModel().getColumn(7).setHeaderValue("Confirmação");
        }

        jLabel23.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel23.setText("Realocar reunião com ID");

        jLabel24.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel24.setText("Para sala");

        jComboBox3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auditório Executivo", "Auditório Master", "Sala de Reuniões", "Coordenação de TI", "Sala da Reitoria", "Auditório - Bloco D" }));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/realocar.png"))); // NOI18N

        javax.swing.GroupLayout gl_pnRealcSala = new javax.swing.GroupLayout(pnRealcSala);
        pnRealcSala.setLayout(gl_pnRealcSala);
        gl_pnRealcSala.setHorizontalGroup(
            gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnRealcSala.createSequentialGroup()
                .addGroup(gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_pnRealcSala.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                            .addGroup(gl_pnRealcSala.createSequentialGroup()
                                .addGroup(gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(gl_pnRealcSala.createSequentialGroup()
                        .addGroup(gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gl_pnRealcSala.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel22))
                            .addGroup(gl_pnRealcSala.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton9)
                                    .addComponent(jLabel23))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(gl_pnRealcSala.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(34, 34, 34))
        );
        gl_pnRealcSala.setVerticalGroup(
            gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnRealcSala.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_pnRealcSala.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_pnRealcSala.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25))
                .addGap(41, 41, 41)
                .addComponent(jButton9)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Salas", pnRealcSala);

        jLabel26.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel26.setText("Reuniões Marcadas");

        jTable6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable6.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(jTable6);
        if (jTable6.getColumnModel().getColumnCount() > 0) {
            jTable6.getColumnModel().getColumn(0).setMinWidth(28);
            jTable6.getColumnModel().getColumn(0).setPreferredWidth(28);
            jTable6.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        jLabel27.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel27.setText("Selecionar reunião com ID");

        jLabel28.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel28.setText("Adicionar participante");

        jButton10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton10.setText("Pesquisar");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        jButton11.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton11.setText("Adicionar participante");

        jLabel30.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel30.setText("Selecionar participante com ID");

        jTable7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Proprietário", "Local", "Sala", "Piso", "Início", "Término", "Confirmação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable7.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(jTable7);
        if (jTable7.getColumnModel().getColumnCount() > 0) {
            jTable7.getColumnModel().getColumn(0).setMinWidth(28);
            jTable7.getColumnModel().getColumn(0).setPreferredWidth(28);
            jTable7.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable7.getColumnModel().getColumn(1).setHeaderValue("Proprietário");
            jTable7.getColumnModel().getColumn(2).setResizable(false);
            jTable7.getColumnModel().getColumn(2).setHeaderValue("Local");
            jTable7.getColumnModel().getColumn(3).setHeaderValue("Sala");
            jTable7.getColumnModel().getColumn(4).setHeaderValue("Piso");
            jTable7.getColumnModel().getColumn(5).setHeaderValue("Início");
            jTable7.getColumnModel().getColumn(6).setHeaderValue("Término");
            jTable7.getColumnModel().getColumn(7).setHeaderValue("Confirmação");
        }

        javax.swing.GroupLayout gl_pnRealcPartList = new javax.swing.GroupLayout(pnRealcPartList);
        pnRealcPartList.setLayout(gl_pnRealcPartList);
        gl_pnRealcPartList.setHorizontalGroup(
            gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnRealcPartList.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_pnRealcPartList.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(gl_pnRealcPartList.createSequentialGroup()
                        .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gl_pnRealcPartList.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jLabel26))
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_pnRealcPartList.createSequentialGroup()
                        .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gl_pnRealcPartList.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gl_pnRealcPartList.createSequentialGroup()
                                .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(gl_pnRealcPartList.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(gl_pnRealcPartList.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton10))
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
            .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gl_pnRealcPartList.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        gl_pnRealcPartList.setVerticalGroup(
            gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnRealcPartList.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(168, 168, 168)
                .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gl_pnRealcPartList.createSequentialGroup()
                        .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jButton10)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(35, 35, 35))
            .addGroup(gl_pnRealcPartList.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gl_pnRealcPartList.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(334, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Participantes", pnRealcPartList);

        javax.swing.GroupLayout gl_pnRealocacoes = new javax.swing.GroupLayout(pnRealocacoes);
        pnRealocacoes.setLayout(gl_pnRealocacoes);
        gl_pnRealocacoes.setHorizontalGroup(
            gl_pnRealocacoes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        gl_pnRealocacoes.setVerticalGroup(
            gl_pnRealocacoes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Realocações ", pnRealocacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioCoordenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioCoordenador().setVisible(true);
                
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnAgReunioes;
    private javax.swing.JPanel pnReunioes;
    private javax.swing.JPanel pnAtas;
    private javax.swing.JPanel pnRealocacoes;
    private javax.swing.JPanel pnRealcSala;
    private javax.swing.JPanel pnRealcPartList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbReunioesConf;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    
    private final Action acMostrarReConfirmadas = new SwingAction();
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "SwingAction");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
			//MetodosEstaticos.ViewTableConf(conect, coordenador, ps, rt, modeloReunioesConf, linhasTbReunioesConf);
			//coordenador.ViewTableConf(conect, ps, rt, modeloReunioesConf, linhasTbReunioesConf);
			try { 
    			ps = conect.prepareStatement("SELECT PERIODO, DATA_REUNIAO, NOME_SALA, PISO, NOME_LOCAL, CIDADE, PARTICIPACAO, IDREUNIAO "  
    					+"FROM SALA "
    					+"INNER JOIN LOCAL "
    					+"ON IDLOCAL = ID_LOCAL "
    					+"INNER JOIN REUNIAO "
    					+"ON IDSALA = ID_SALA "
    					+"INNER JOIN USUARIO__REUNIAO "
    					+"ON ID_REUNIAO = IDREUNIAO "
    					+"WHERE PARTICIPACAO = ? AND ID_USUARIO = ? ");
    			ps.setString(1, "SIM");
    			ps.setInt(2, coordenador.getIdUser());
    			rt = ps.executeQuery();
    			while(rt.next()) { 
    				//String local, sala, nome, periodo, confirmacao, piso , data;
    				linhasTbReunioesConf[0] = rt.getInt("IDREUNIAO");
    				linhasTbReunioesConf[1] = rt.getString("DATA_REUNIAO");
    				linhasTbReunioesConf[2] = rt.getString("PERIODO");
    				linhasTbReunioesConf[3] = rt.getString("NOME_LOCAL");
    				linhasTbReunioesConf[4] = rt.getString("CIDADE");
    				linhasTbReunioesConf[5] = rt.getString("NOME_SALA");
    				linhasTbReunioesConf[6] = rt.getString("PISO");
    				modeloReunioesConf.addRow(linhasTbReunioesConf);
    		}
    		
    	} catch (SQLException eVisualizarReConf) {
    		eVisualizarReConf.printStackTrace();
    	 }
		}
	}
}
