/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import modelo.Comum;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import javax.swing.JFormattedTextField;
import java.awt.Font;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JList;
import javax.swing.JSeparator;
import javax.swing.JSplitPane;
import javax.swing.JPasswordField;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import javax.swing.Action;

/**
 *
 * @author Carlos Jr
 */
public class UsuarioComum extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioComum
     */
	
	JLabel lbConfirmacaoCadastro;
	JFormattedTextField ftCpfCadastro;
    private javax.swing.JTextField tfNomeCadastro;
    private javax.swing.JTextField tfEmailCadastro;
    private JPasswordField ptSenhaCadastro;
    private JPasswordField ptConSenhaCadastro;
    private javax.swing.JComboBox cbTipoUsuarioCadastro;

	
    public UsuarioComum() {
        initComponents();
    }
    
 // Declarando objetos uteis
 	Statement st = null;
 	PreparedStatement ps = null;
 	ResultSet rt = null;
 	Comum usuario ;
 	Connection conect = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnReuniao = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        //jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox();
        jTextField15 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnVisualizacao = new javax.swing.JPanel();
       // jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnCadastro = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNomeCadastro = new javax.swing.JTextField();
        cbTipoUsuarioCadastro = new javax.swing.JComboBox();
        cbTipoUsuarioCadastro.setEnabled(false);
        tfEmailCadastro = new javax.swing.JTextField();
        btCancelarCadastro = new javax.swing.JButton();
        btSalvarCadastro = new javax.swing.JButton();
        btSalvarCadastro.setAction(cadastrarUsuario);
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("e-Meeting - Usuário Comum");

        jTabbedPane1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel8.setText("Reservar Reunião");

        jLabel9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel9.setText("Data");

        jLabel10.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel10.setText("In\u00EDcio");

        jButton5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton5.setText("Cancelar");

        jButton6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton6.setText("Confirmar");

        jComboBox5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        
        JFormattedTextField formattedTextField = new JFormattedTextField();
        
        JLabel lblDurao = new JLabel();
        lblDurao.setText("Dura\u00E7\u00E3o");
        lblDurao.setFont(new Font("Candara", Font.BOLD, 14));
        
        JComboBox comboBox = new JComboBox();
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"1h", "2h", "3h", "4h", "5h", "6h", "7h", "8h", "9h", "10h", "11h", "12h", "13h", "14h", "15h"}));
        comboBox.setFont(new Font("Calibri", Font.BOLD, 14));
        
        JLabel lblIdLocal = new JLabel();
        lblIdLocal.setText("ID Local");
        lblIdLocal.setFont(new Font("Candara", Font.BOLD, 14));
        
        textField = new JTextField();
        textField.setColumns(10);
        
        JLabel lblSala = new JLabel();
        lblSala.setText("Sala");
        lblSala.setFont(new Font("Candara", Font.BOLD, 14));
        
        textField_1 = new JTextField();
        textField_1.setColumns(10);
        
        JLabel lblDescrio = new JLabel();
        lblDescrio.setText("Descri\u00E7\u00E3o");
        lblDescrio.setFont(new Font("Candara", Font.BOLD, 14));
        
        textField_2 = new JTextField();
        textField_2.setColumns(10);
        jComboBox4 = new javax.swing.JComboBox();
        
                jComboBox4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                jComboBox4.setModel(new DefaultComboBoxModel(new String[] {"P\u00FAblico", "Privado"}));
        jLabel23 = new javax.swing.JLabel();
        
                jLabel23.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
                jLabel23.setText("Acesso");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8Layout.setHorizontalGroup(
        	jPanel8Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel8Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel8Layout.createSequentialGroup()
        					.addComponent(lblIdLocal, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(234, Short.MAX_VALUE))
        				.addGroup(jPanel8Layout.createSequentialGroup()
        					.addComponent(lblSala, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(234, Short.MAX_VALUE))
        				.addGroup(jPanel8Layout.createSequentialGroup()
        					.addComponent(lblDescrio, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(226, Short.MAX_VALUE))
        				.addGroup(jPanel8Layout.createSequentialGroup()
        					.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel9)
        						.addComponent(jLabel10)
        						.addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(formattedTextField, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textField_2, GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        						.addGroup(jPanel8Layout.createSequentialGroup()
        							.addGap(97)
        							.addComponent(jLabel8)))
        					.addContainerGap())
        				.addGroup(jPanel8Layout.createSequentialGroup()
        					.addGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(textField_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        						.addComponent(textField, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        					.addGap(140))
        				.addGroup(jPanel8Layout.createSequentialGroup()
        					.addGap(31)
        					.addComponent(jButton5)
        					.addPreferredGap(ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
        					.addComponent(jButton6)
        					.addGap(25))
        				.addGroup(jPanel8Layout.createSequentialGroup()
        					.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel8Layout.createSequentialGroup()
        							.addComponent(comboBox, 0, 72, Short.MAX_VALUE)
        							.addGap(91))
        						.addGroup(jPanel8Layout.createSequentialGroup()
        							.addComponent(lblDurao, GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        							.addGap(89)))
        					.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel23)
        						.addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
        					.addGap(20))))
        );
        jPanel8Layout.setVerticalGroup(
        	jPanel8Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel8Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel8)
        			.addGap(18)
        			.addComponent(jLabel9)
        			.addGap(4)
        			.addComponent(formattedTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel10)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblDurao, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel23))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblIdLocal, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblSala, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblDescrio, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(textField_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        			.addGroup(jPanel8Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton5)
        				.addComponent(jButton6))
        			.addGap(23))
        );
        jPanel8.setLayout(jPanel8Layout);

        jLabel18.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel18.setText("Pesquisar Local");

        jLabel19.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel19.setText("Nome do Local");

        jLabel20.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel20.setText("Estado");

        jComboBox7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jComboBox7.setModel(new DefaultComboBoxModel(new String[] {"PB", "RN", "CE", "AL", "RJ", "BH", "SP"}));

        jButton9.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton9.setText("Pesquisar");
        jButton9.setMargin(new java.awt.Insets(5, 14, 2, 14));

        jLabel24.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel24.setText("Cidade");
        
        btnLimpar = new JButton();
        btnLimpar.setText("Limpar");
        btnLimpar.setMargin(new Insets(5, 14, 2, 14));
        btnLimpar.setFont(new Font("Candara", Font.BOLD, 14));
        
        lblDadosDoLocal = new JLabel();
        lblDadosDoLocal.setText("Dados do Local");
        lblDadosDoLocal.setFont(new Font("Candara", Font.BOLD, 14));
        
        list = new JList();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9Layout.setHorizontalGroup(
        	jPanel9Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jTextField14, 280, 280, 280)
        		.addGroup(jPanel9Layout.createSequentialGroup()
        			.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jComboBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel19)
        				.addGroup(jPanel9Layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(jLabel24, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jLabel20, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
        			.addContainerGap(190, Short.MAX_VALUE))
        		.addGroup(jPanel9Layout.createSequentialGroup()
        			.addContainerGap(81, Short.MAX_VALUE)
        			.addComponent(jLabel18, GroupLayout.PREFERRED_SIZE, 106, GroupLayout.PREFERRED_SIZE)
        			.addGap(93))
        		.addComponent(jTextField15, GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        		.addGroup(jPanel9Layout.createSequentialGroup()
        			.addGap(27)
        			.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(jPanel9Layout.createSequentialGroup()
        					.addGap(36)
        					.addComponent(jButton9)
        					.addGap(18)
        					.addComponent(btnLimpar, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel9Layout.createSequentialGroup()
        					.addGap(62)
        					.addComponent(lblDadosDoLocal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addContainerGap(31, Short.MAX_VALUE))
        		.addGroup(jPanel9Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(list, GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
        	jPanel9Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel9Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel18)
        			.addGap(23)
        			.addComponent(jLabel19)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jTextField14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel20)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jComboBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(16)
        			.addComponent(jLabel24)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jTextField15, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel9Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton9, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnLimpar, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(lblDadosDoLocal, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(list, GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        			.addGap(35))
        );
        jPanel9.setLayout(jPanel9Layout);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout gl_pnReuniao = new javax.swing.GroupLayout(pnReuniao);
        pnReuniao.setLayout(gl_pnReuniao);
        gl_pnReuniao.setHorizontalGroup(
            gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
            .addGroup(gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gl_pnReuniao.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        gl_pnReuniao.setVerticalGroup(
            gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
            .addGroup(gl_pnReuniao.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gl_pnReuniao.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 44, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Reuniões", pnReuniao);

        jButton11.setText("Adicionar");

        jButton12.setText("Excluir");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Segunda", "TerÃ§a", "Quarta", "Quinta", "Sexta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout gl_pnVisualizacao = new javax.swing.GroupLayout(pnVisualizacao);
        gl_pnVisualizacao.setHorizontalGroup(
        	gl_pnVisualizacao.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_pnVisualizacao.createSequentialGroup()
        			.addGap(32)
        			.addComponent(jButton11)
        			.addPreferredGap(ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
        			.addComponent(jButton12)
        			.addGap(53))
        		.addGroup(Alignment.LEADING, gl_pnVisualizacao.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        			.addContainerGap())
        );
        gl_pnVisualizacao.setVerticalGroup(
        	gl_pnVisualizacao.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, gl_pnVisualizacao.createSequentialGroup()
        			.addGap(24)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 404, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
        			.addGroup(gl_pnVisualizacao.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton11)
        				.addComponent(jButton12))
        			.addGap(35))
        );
        pnVisualizacao.setLayout(gl_pnVisualizacao);

        jTabbedPane1.addTab("Vizualizar Reuniões", pnVisualizacao);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Usu\u00E1rio");

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText("Perfil de Acesso");

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setText("CPF");

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setText("E-mail");

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setText("Senha");

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setText("Confirme a senha");

        cbTipoUsuarioCadastro.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        cbTipoUsuarioCadastro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comum", "Coordenador", "Gestor de Recursos" }));

        tfEmailCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        btCancelarCadastro.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btCancelarCadastro.setText("Cancelar");

        btSalvarCadastro.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        btSalvarCadastro.setText("Salvar");
        
        lbConfirmacaoCadastro = new JLabel("Verifique seus dados antes de salvar");
        
        ftCpfCadastro = new JFormattedTextField();
        
        ptSenhaCadastro = new JPasswordField();
        
        ptConSenhaCadastro = new JPasswordField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGap(86)
        							.addComponent(jLabel1))
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGap(36)
        							.addComponent(btCancelarCadastro)
        							.addGap(54)
        							.addComponent(btSalvarCadastro)))
        					.addGap(0, 66, Short.MAX_VALUE))
        				.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(tfNomeCadastro, 300, 300, 300)
        						.addComponent(cbTipoUsuarioCadastro, 0, 300, Short.MAX_VALUE)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(263))
        						.addComponent(tfEmailCadastro, 300, 300, 300)
        						.addGroup(jPanel5Layout.createSequentialGroup()
        							.addGroup(jPanel5Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel2, Alignment.LEADING)
        								.addComponent(jLabel3, Alignment.LEADING)
        								.addComponent(jLabel4, Alignment.LEADING)
        								.addComponent(jLabel5, Alignment.LEADING))
        							.addGap(0, 205, Short.MAX_VALUE))))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel7))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(ftCpfCadastro, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(ptSenhaCadastro, GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(ptConSenhaCadastro, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel5Layout.createSequentialGroup()
        					.addGap(48)
        					.addComponent(lbConfirmacaoCadastro, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel5Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tfNomeCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cbTipoUsuarioCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel4)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(ftCpfCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(9)
        			.addComponent(jLabel5)
        			.addGap(2)
        			.addComponent(tfEmailCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel6)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(ptSenhaCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jLabel7)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(ptConSenhaCadastro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(29)
        			.addComponent(lbConfirmacaoCadastro, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        			.addGap(41)
        			.addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btCancelarCadastro)
        				.addComponent(btSalvarCadastro))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5.setLayout(jPanel5Layout);

        jLabel15.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel15.setText("Pesquisar Usu\u00E1rio");

        jLabel16.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel16.setText("CPF");

        jLabel17.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel17.setText("Dados do usu\u00E1rio:");

        jButton3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton3.setText("Pesquisar");

        jButton4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButton4.setText("Limpar");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeSettings.png"))); // NOI18N
        
        JTextPane textPane = new JTextPane();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap(120, Short.MAX_VALUE)
        			.addComponent(jLabel13)
        			.addGap(93))
        		.addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jTextField7, Alignment.LEADING, 329, 329, 329)
        				.addComponent(jLabel16, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        				.addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
        					.addGap(110)
        					.addComponent(jLabel15))
        				.addComponent(jLabel17, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
        				.addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
        					.addGap(71)
        					.addComponent(jButton3)
        					.addGap(45)
        					.addComponent(jButton4)))
        			.addContainerGap(12, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, jPanel6Layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(textPane, GroupLayout.PREFERRED_SIZE, 302, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel15)
        			.addGap(18)
        			.addComponent(jLabel16)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(33)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton3)
        				.addComponent(jButton4))
        			.addGap(38)
        			.addComponent(jLabel17)
        			.addGap(11)
        			.addComponent(textPane, GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        			.addGap(18)
        			.addComponent(jLabel13)
        			.addGap(35))
        );
        jPanel6.setLayout(jPanel6Layout);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout gl_pnCadastro = new javax.swing.GroupLayout(pnCadastro);
        pnCadastro.setLayout(gl_pnCadastro);
        gl_pnCadastro.setHorizontalGroup(
            gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_pnCadastro.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        gl_pnCadastro.setVerticalGroup(
            gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_pnCadastro.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, gl_pnCadastro.createSequentialGroup()
                        .addGroup(gl_pnCadastro.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastros", pnCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        
        pnAta = new JPanel();
        jTabbedPane1.addTab("Atas", null, pnAta, null);
        
        pnPlanoDeAcao = new JPanel();
        jTabbedPane1.addTab("Plano de Ação", null, pnPlanoDeAcao, null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioComum().setVisible(true);
            }
        });
    }
    
    public void receberUsuario(Comum userComum) {
		System.out.println("Recebendo o objeto usuario!");
		usuario = userComum;	
	}
	
	public void receberConeccao(Connection con) {
		conect = con;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarCadastro;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton btSalvarCadastro;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox7;
   // private com.toedter.calendar.JDateChooser jDateChooser1;
   // private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnCadastro;
    private javax.swing.JPanel pnReuniao;
    private javax.swing.JPanel pnVisualizacao;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField7;
    private JPanel pnAta;
    private JPanel pnPlanoDeAcao;
    private JTextField textField;
    private JTextField textField_1;
    private JTextField textField_2;
    private JButton btnLimpar;
    private JLabel lblDadosDoLocal;
    private JList list;
    
   
    // Definindo açoes
    private final Action cadastrarUsuario = new SwingAction();
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "Salvar");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}
		public void actionPerformed(ActionEvent e) {
			String nome, cpf, email, senha, confirmarSenha, tipoUsuario;
			nome = tfNomeCadastro.getText();
			cpf = ftCpfCadastro.getText();
			email = tfEmailCadastro.getText();
			senha = ptSenhaCadastro.getText();
			confirmarSenha = ptConSenhaCadastro.getText();
			tipoUsuario = ((String) cbTipoUsuarioCadastro.getSelectedItem()); // casting de Object para String
			System.out.println((String) cbTipoUsuarioCadastro.getSelectedItem()); // esse mesmo!
			System.out.println("Tipo de usuario: "+tipoUsuario);
			if(senha.equals(confirmarSenha)) {
				// entrar com o metodo de cadastrar usuario!
				usuario.cadastrarUsuario(conect, ps, rt, nome, cpf, confirmarSenha, email, tipoUsuario);
				lbConfirmacaoCadastro.setText("As senhas são iguais");
				
			}else {
				lbConfirmacaoCadastro.setText("Senhas diferentes, digite as novamente!");
			}
			System.out.println("Dados:");
			System.out.println("Nome: "+nome+", Cpf: "+cpf+", Email"+email+"\nSehna: "+senha+", Confirmar Senha"+confirmarSenha);
			
		}
	}
}
